name: compete
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^1.11.5
  cloud_firestore: ^1.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flutter_bloc: ^7.0.0
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  google_fonts: ^2.0.0
  injectable: ^1.2.0
  curved_navigation_bar: ^0.4.0-nullsafety.0
  uuid: ^3.0.4 


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  injectable_generator: ^1.2.0

flutter:
  uses-material-design: true

